import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import Header from "@/components/Header";
import ReduxWrapper from "@/redux/ReduxWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxWrapper>
          <ClerkProvider>
            <Header />
            {children}
          </ClerkProvider>
          <SanityLive />
        </ReduxWrapper>
      </body>
    </html>
  );
}
